### PR TITLE
SQL injection fix: Coerce offset and limit values to integers

### LINKED ISSUE #1052: SQL injection possible with limit() on MySQL
**The `limit()` query method is susceptible to catastrophic SQL injection with MySQL.**

For example, given a model `User` for a table `users`:
```php
UserQuery::create()->limit('1;DROP TABLE users')->find();
```
This will drop the `users` table!

The cause appears to be a lack of integer casting of the limit input in either [`Criteria::setLimit()`](https://github.com/propelorm/Propel/blob/master/runtime/lib/query/Criteria.php#L1240-L1246) or in [`DBMySQL::applyLimit()`](https://github.com/propelorm/Propel/blob/master/runtime/lib/adapter/DBMySQL.php#L154-L161). The code comments there seem to imply that casting was avoided due to overflow issues with 32-bit integers.

This is surprising behavior since one of the primary purposes of an ORM is to prevent basic SQL injection.

**This affects all versions of Propel: 1.x, 2.x, and 3.**

Related:
- https://github.com/propelorm/Propel2/issues/1463
- https://github.com/propelorm/Propel3/issues/73

### PR DESCRIPTION
**Pull request by mpetrovich**
SQL injection
---
When constructing a MySQL LIMIT clause, values for the offset and limit are coerced to integers. This prevents arbitrary SQL from being injected via a query limit. Example:
```php
UserQuery::create()->limit('1;DROP TABLE users')->find();
```
Previously, this would have injected `DROP TABLE users` into the generated SQL. Now, the limit value would be coerced to the integer `1`.

This is similar to the [fix for Propel2](https://github.com/propelorm/Propel2/pull/1464).

Fixes #1052

Build fixes
---
These changes also fix errors that occurred during build/test, and also add PHPUnit as a dev dependency instead of forcing contributors to download it separately.

Related documentation changes: https://github.com/propelorm/Propel/pull/1055

### CODE REVIEW

**Comment by mpetrovich** [comment]
The build failures seem to be for completely unrelated tests.

File: runtime/lib/query/Criteria.php [hunk 1]
```diff
@@ -1239,8 +1239,7 @@ public function isSingleRecord()
      */
     public function setLimit($limit)
     {
-        // TODO: do we enforce int here? 32bit issue if we do
-        $this->limit = $limit;
+        $this->limit = (int) $limit;
```
Comment (mpetrovich) [inline runtime/lib/query/Criteria.php]: _Maintainers:_
Can anyone provide some context around this comment? My unit tests show that no truncation occurs for large values like 64-bit integers.

**Comment by mpetrovich** [comment]
I could use help from the maintainers on figuring out why that unrelated test is failing. Not sure if it's a red herring or a legit failure.

**Comment by mpetrovich** [comment]
Ah, great to know! I'll update the travis config.

**Comment by smhg** [comment]
@mpetrovich I've looked into the encoding failure while trying to fix the tests in my own branch.
It was introduced in [this commit](https://github.com/propelorm/Propel/commit/62afa323b2f1eb67b27fd11e5954873f74108b61) after the release of 1.7.1.

The solution is to add `SET NAMES utf8;` at the top of **test/fixtures/reverse/mysql/build/sql/schema.sql** so the utf8 characters in that file are correctly sent to MySQL.

You can try it out with [my branch](https://github.com/smhg/Propel/tree/fix-tests-php7).

**Comment by erickr** [comment]
@willdurand Any chance we could get this merged and released as 1.7.2?

**Comment by mpetrovich** [comment]
bump

**Comment by mpetrovich** [comment]
tumbleweed

**Comment by smhg** [comment]
@mpetrovich and others affected: did you somehow get in touch with anyone concerning Propel1 in the (recent) past?
Do you think it makes sense to put a bit more effort in this?
We can/should discuss somewhere else of course (if there is anything to discuss).

**Comment by mpetrovich** [comment]
@smhg Can't hurt to try harder. I DMed @staabm on Twitter and will try @willdurand next if we don't have any luck. It shouldn't be a big ask for either of them—releasing a new patch version is usually just a few keystrokes.

**Comment by staabm** [comment]
Will build a release tomorrow

**Comment by mpetrovich** [comment]
🙌 Thank you!
